name: Schema Up to date
on: 
  push: 
    branches:
      - master
      - trial
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install build-essential
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' 
          architecture: 'x64'
      - run: make init
      - id : color
        run: echo $(python schema.py --color)
      - id : tag
        run : echo $(python schema.py --tag)
      - name: create badge
        uses: RubbaBoy/BYOB@v1.1.0
        with:
          NAME: Schema
          LABEL: 'Schema Up to date'
          STATUS: ${{ steps.tag.outputs.data }}
          COLOR: ${{ steps.color.outputs.data }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}