name: Schema Up to date
on: 
  push: 
    branches:
      - master
      - trial
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install build-essential
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' 
          architecture: 'x64'